server:
  port: 56010
spring:
  application:
    name: nacos-restful-provider  # 服务名。
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 服务中心地址。
#        server-addr: 192.168.142.161:8848  # 服务中心地址。
